import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<header className="bg-sky-600 min-h-[100px] flex flex-col justify-center items-center">
					<h1 className="text-white text-4xl">Can I joke on you?</h1>
				</header>
				<main className="flex flex-col items-center justify-between w-full">{children}</main>
			</body>
		</html>
	);
}
