/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 billy-tankMaterial-properanims.glb --types 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    body001: THREE.SkinnedMesh
    ['seed-o-gun_Cube010mesh017']: THREE.SkinnedMesh
    ['seed-o-gun_Cube010mesh017_1']: THREE.SkinnedMesh
    mixamorigHips: THREE.Bone
  }
  materials: {
    Billy: THREE.MeshBasicMaterial
    Billy: THREE.MeshBasicMaterial
    ['Pistol Tank']: THREE.MeshBasicMaterial
  }
}

type ActionName = 'win' | 'rifleidle' | 'fire' | 'downtoaim' | 'aimtodown' | 'idle'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['skinnedMesh'] | JSX.IntrinsicElements['bone']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/billy-tankMaterial-properanims.glb') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Billy">
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="body001" geometry={nodes.body001.geometry} material={materials.Billy} skeleton={nodes.body001.skeleton} />
          <group name="pistol">
            <skinnedMesh name="seed-o-gun_Cube010mesh017" geometry={nodes['seed-o-gun_Cube010mesh017'].geometry} material={materials.Billy} skeleton={nodes['seed-o-gun_Cube010mesh017'].skeleton} />
            <skinnedMesh name="seed-o-gun_Cube010mesh017_1" geometry={nodes['seed-o-gun_Cube010mesh017_1'].geometry} material={materials['Pistol Tank']} skeleton={nodes['seed-o-gun_Cube010mesh017_1'].skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/billy-tankMaterial-properanims.glb')
